// node tools/cosmetics/build.mjs: builds every cosmetic into cosmetics.json for Nimbus Core
// and a copy for the launcher's previews.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import hats from './hats.mjs';
import pets from './pets.mjs';
import wings from './wings.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const items = [...hats, ...pets, ...wings];
const RARITIES = ['common', 'rare', 'epic', 'legendary', 'mythic'];
const SLOTS = ['hat', 'pet', 'wings', 'aura'];

const ids = new Set();
let boxes = 0;
const round = (n) => Math.round(n * 100) / 100;
function clean(p) {
  const out = { p: p.p.map(round) };
  if (p.r) out.r = p.r.map(round);
  if (p.s) out.s = round(p.s);
  if (p.a) out.a = p.a;
  if (p.b) { out.b = p.b.map((b) => [...b.slice(0, 6).map(round), b[6] >>> 0, b[7] | 0, b[8] ?? 63]); boxes += p.b.length; }
  if (p.c) out.c = p.c.map(clean);
  return out;
}
for (const it of items) {
  if (!/^[a-z0-9_]{2,40}$/.test(it.id)) throw new Error(`bad id ${it.id}`);
  if (ids.has(it.id)) throw new Error(`duplicate id ${it.id}`);
  ids.add(it.id);
  if (!SLOTS.includes(it.slot)) throw new Error(`${it.id}: bad slot ${it.slot}`);
  if (!RARITIES.includes(it.rarity)) throw new Error(`${it.id}: bad rarity ${it.rarity}`);
}
const out = {
  version: 1,
  items: items.map((it) => ({ id: it.id, name: it.name, slot: it.slot, rarity: it.rarity, desc: it.desc, parts: it.parts.map(clean), fx: it.fx || [] })),
};
const json = JSON.stringify(out);
fs.mkdirSync(path.join(root, 'mod/common/src/main/resources/assets/nimbus'), { recursive: true });
fs.writeFileSync(path.join(root, 'mod/common/src/main/resources/assets/nimbus/cosmetics.json'), json);
fs.writeFileSync(path.join(root, 'src/renderer/js/cosmetics-data.js'), `// Generated by tools/cosmetics/build.mjs. Do not edit.\nexport default ${json};\n`);
const bySlot = Object.fromEntries(SLOTS.map((s) => [s, items.filter((i) => i.slot === s).length]));
console.log(`${items.length} cosmetics`, bySlot, `${boxes} boxes, ${(json.length / 1024).toFixed(0)} KB`);
const big = out.items.map((it) => { let n = 0; const walk = (p) => { n += (p.b || []).length; (p.c || []).forEach(walk); }; it.parts.forEach(walk); return [it.id, n]; }).sort((a, b) => b[1] - a[1]).slice(0, 5);
console.log('largest:', big.map(([i, n]) => `${i} ${n}`).join(', '));
